spring:
  h2:
    console:
      enabled: true
#      path: /h2
      settings:
       web-allow-others: false
  datasource:
    url: jdbc:h2:./exdb;MODE=PostgreSQL
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

